######################################################################
# Automatically generated by qmake (2.01a) Fri May 1 17:27:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
